### ISSUE TITLE
Some of cfgmgr32.h's member has obsolete

### ISSUE THREAD

**Issue by captainww** [hedgar2017/loki-hidriver#4]
Thanks anyway

**Comment by RenanErnest** [comment]
I am still struggling with this, how did you make it work?

**Comment by captainww** [comment]
#ENVIRONMENT     QT 5.9 with WDK 10.0.15063 

Well I've tried use 'extern "C" #include hidsdi.h' in "device.cpp" and wrote absolute path of  *.lib in "example.pro".

Then it works.
