### ISSUE TITLE
How to build and run

### ISSUE THREAD

**Issue by l278943941** [hedgar2017/loki-hidriver#5]
debug win10.0.14393.0 64-bit

Build successful but unable to start service

![err](https://user-images.githubusercontent.com/13584151/71457946-74da3500-27db-11ea-9850-4323b088b87c.png)
![error photo](https://github.com/l278943941/photos/blob/master/err.png)

**Comment by l278943941** [comment]
https://github.com/l278943941/photos/blob/master/err.png

`

**Comment by captainww** [comment]
We're in the same trouble
Cfgmgr32.h has updated see issues 4
I'm not solve it yet
How do you build the driver? WDK also updated.

**Comment by l278943941** [comment]
vs2015 debug win10.0.14393.0 64-bit  
Warning level /w0 
Dirver Setting target Platform Desktop

**Comment by captainww** [comment]
Do you know how to fix the driver interface?

**Comment by l278943941** [comment]
sorry 我英文不好 你上一句我没看懂

**Comment by captainww** [comment]
搁这儿闹了半天原来都是说中文的
要是你还没编译好驱动这位写驱动的老哥上传了他编译好的驱动文件https://github.com/hedgar2017/loki-hidriver-release
手动安装就行了
现在的问题是cfgmgr32.h的更新弃用了几个函数
这位老哥提供的驱动接口需要改一下才能用
要是你能写驱动接口（记得给我发一份哈）就没什么问题了

**Comment by l278943941** [comment]
编译好了 但是跑不起来
他自带的安装工具显示 
InitSideBySide failed create an activation context. Error: 1814
我用我写的安装工具 Error: 1058
演示用例 要用qt编译的 最起码也要用QT转vs 我的演示程序是 能跑起来的但是驱动跑不起来
还有就是你驱动能跑起来么 是什么版本的windows

**Comment by captainww** [comment]
我的是win10 18362 64bit
自己尝试编译了一下发现需要改动太多地方干脆用他编译好的驱动文件手动安装成功了
可以在设备里看到安装好的驱动
但是我还没有解决演示程序的问题所以现在没有办法验证驱动能不能跑起来
演示程序我直接跑的c源码

**Comment by l278943941** [comment]
请问有没有禁用驱动签名
我把打包后的示例传上来了
https://github.com/l278943941/photos/blob/master/loki-example.exe

**Comment by captainww** [comment]
貌似没有 直接开测试模式就安装成功了
多谢哈

**Comment by captainww** [comment]
老哥 能不能给份源码呀
只是一个接口 问题不大吧

**Comment by l278943941** [comment]
源码你不是有么 装个qt就能编译了 什么都不用改啊

**Comment by captainww** [comment]
是这样的 我安装的是最新版本的wdk 还是用手机网络连的网 现在也没机会重新下载低版本的wdk vs也是2019的
写驱动的老哥提供的演示程序在新版本的wdk环境下需要改一下才能用

**Comment by captainww** [comment]
我是用mingw编译的 演示程序需要用的包都自动更新了
看来只能安装低版本的环境了

**Comment by l278943941** [comment]
我是用的msvc2015 64 编译的 你跑了示例后 起作用了么 我这个貌似还是装不上

**Comment by captainww** [comment]
我这边是能安装成功 因为还在搞版本更新的问题 没法验证
你是安装不上还是测试通不过

**Comment by l278943941** [comment]
能安装上 但是无法启动服务

**Comment by captainww** [comment]
这就没招了 这个项目年久失修作者不维护了 撤吧

**Comment by captainww** [comment]
要不要加个什么交流下
我感觉我们做的东西差不多

**Comment by captainww** [comment]
https://github.com/djpnewton/vmulti
这个不错

**Comment by l278943941** [comment]
好呀 我qq278943942

**Comment by hedgar2017** [comment]
It can be really tricky and issue-prone to build the driver from scratch. Please, check the loki-hidriver-release repo for the binaries.
